src/Georest.Web/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using AutoMapper;
using Georest.Web.ApiViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Georest.Web.Controllers
{
    public class ExercisesController : Controller
    {
        private IHttpClientFactory ClientFactory { get; }
        private IMapper Mapper { get; }
        public ExercisesController(IHttpClientFactory clientFactory, IMapper mapper)
        {
            ClientFactory = clientFactory;
            Mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                ViewBag.Exercises = await georestClient.GetAllExercisesAsync();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(ExerciseInputViewModel viewModel)
        {
            IActionResult result = View();

            if (ModelState.IsValid)
            {
                using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
                {
                    try
                    {
                        var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                        await georestClient.AddExerciseAsync(viewModel);

                        result = RedirectToAction(nameof(Index));
                    }
                    catch (SwaggerException se)
                    {
                        ModelState.AddModelError("", se.Message);
                    }
                }
            }

            return result;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ExerciseViewModel fetchedExercise = null;

            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                try
                {
                    var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                    fetchedExercise = await georestClient.GetExerciseByIdAsync(id);
                }
                catch (SwaggerException se)
                {
                    ModelState.AddModelError("", se.Message);
                }
            }
            return View(fetchedExercise);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ExerciseViewModel viewModel)
        {
            IActionResult result = View();

            if (ModelState.IsValid)
            {
                using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
                {
                    try
                    {
                        var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                        await georestClient.UpdateExerciseAsync(viewModel.Id, Mapper.Map<ExerciseInputViewModel>(viewModel));

                        result = RedirectToAction(nameof(Index));
                    }
                    catch (SwaggerException se)
                    {
                        ModelState.AddModelError("", se.Message);
                    }
                }
            }

            return result;
        }

        public async Task<IActionResult> Delete(int id)
        {
            IActionResult result = View();
            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                try
                {
                    var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                    await georestClient.DeleteExerciseAsync(id);

                    result = RedirectToAction(nameof(Index));
                }
                catch (SwaggerException se)
                {
                    ModelState.AddModelError("", se.Message);
                }
            }

            return result;
        }
    }
}

src/Georest.Web/Views/Exercises/Add.cshtml
@model ExerciseInputViewModel

<div asp-validation-summary="All"></div>
<form asp-route="Add">
    <div class="field">
        <label class="label" asp-for="Title">Exercise Title</label>
        <div class="control">
            <input class="input" type="text" asp-for="Title" />
        </div>
    </div>
    <div class="field">
        <label class="label" asp-for="Body">Exercise Body</label>
        <div class="control">
            <input class="input" type="text" asp-for="Body" />
        </div>
    </div>
    <div class="field">
        <div class="control is-grouped">
            <button class="button is-primary">Submit</button>
        </div>
        <div class="control">
            <a asp-controller="Exercises" asp-action="Index" class="button is-light">Cancel</a>
        </div>
    </div>
</form>

src/Georest.Web/Views/Exercises/Edit.cshtml
@model ExerciseViewModel

<div asp-validation-summary="All"></div>
<form asp-route="Edit">
    <input asp-for="Id" type="hidden" />
    <div class="field">
        <label class="label" asp-for="Title">Exercise Title</label>
        <div class="control">
            <input class="input" type="text" asp-for="Title" />
        </div>
    </div>
    <div class="field">
        <label class="label" asp-for="Body">Exercise Body</label>
        <div class="control">
            <input class="input" type="text" asp-for="Body" />
        </div>
    </div>
    <div class="field is-grouped">
        <div class="control">
            <button class="button is-primary">Submit</button>
        </div>
        <div class="control">
            <a asp-controller="Exercises" asp-action="Index" class="button is-light">Cancel</a>
        </div>
    </div>
</form>

src/Georest.Web/Views/Exercises/Index.cshtml
<h1 class="heading is-size-3 is-bold">Exercises<br /></h1>
<ul>
    @if (ViewBag.Exercises.Count == 0)
    {
        <li>No Exercises</li>
    }
    @foreach (var exercise in ViewBag.Exercises)
    {
        <li>
            <br />
            <h1 class="heading is-size-4 is-bold">@exercise.Id. @exercise.Title<br /></h1>
            @exercise.Body<br />
            <a class="button" asp-action="edit" asp-route-id="@exercise.Id">Edit</a>
            <a class="button is-danger" asp-action="delete" asp-route-id="@exercise.Id" onclick="return confirm('Are you sure you want to delete the exercise @exercise.Title?')">Delete</a>
        </li>
    }
</ul>
<a asp-controller="Exercises" asp-action="Add" class="button is-primary">Add Exercise</a>