src/Georest.Web/Controllers/InstructorLabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using AutoMapper;
using Georest.Web.ApiViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Georest.Web.Controllers
{
    public class InstructorLabsController : Controller
    {
        private IHttpClientFactory ClientFactory { get; }
        private IMapper Mapper { get; }
        public InstructorLabsController(IHttpClientFactory clientFactory, IMapper mapper)
        {
            ClientFactory = clientFactory;
            Mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                ViewBag.InstructorLabs = await georestClient.GetAllLabsAsync();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(InstructorLabInputViewModel viewModel)
        {
            IActionResult result = View();

            if (ModelState.IsValid)
            {
                using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
                {
                    try
                    {
                        var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                        await georestClient.AddLabAsync(viewModel);

                        result = RedirectToAction(nameof(Index));
                    }
                    catch (SwaggerException se)
                    {
                        ModelState.AddModelError("", se.Message);
                    }
                }
            }

            return result;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            InstructorLabViewModel fetchedInstructorLab = null;

            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                try
                {
                    var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                    fetchedInstructorLab = await georestClient.GetLabByIdAsync(id);
                }
                catch (SwaggerException se)
                {
                    ModelState.AddModelError("", se.Message);
                }
            }
            return View(fetchedInstructorLab);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InstructorLabViewModel viewModel)
        {
            IActionResult result = View();

            if (ModelState.IsValid)
            {
                using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
                {
                    try
                    {
                        var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                        await georestClient.UpdateLabAsync(viewModel.Id, Mapper.Map<InstructorLabInputViewModel>(viewModel));

                        result = RedirectToAction(nameof(Index));
                    }
                    catch (SwaggerException se)
                    {
                        ModelState.AddModelError("", se.Message);
                    }
                }
            }

            return result;
        }

        public async Task<IActionResult> Delete(int id)
        {
            IActionResult result = View();
            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                try
                {
                    var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                    await georestClient.DeleteLabAsync(id);

                    result = RedirectToAction(nameof(Index));
                }
                catch (SwaggerException se)
                {
                    ModelState.AddModelError("", se.Message);
                }
            }

            return result;
        }
    }
}

src/Georest.Web/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using AutoMapper;
using Georest.Web.ApiViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Georest.Web.Controllers
{
    public class InstructorsController : Controller
    {
        private IHttpClientFactory ClientFactory { get; }
        private IMapper Mapper { get; }
        public InstructorsController(IHttpClientFactory clientFactory, IMapper mapper)
        {
            ClientFactory = clientFactory;
            Mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                ViewBag.Instructors = await georestClient.GetAllInstructorsAsync();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(InstructorInputViewModel viewModel)
        {
            IActionResult result = View();

            if (ModelState.IsValid)
            {
                using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
                {
                    try
                    {
                        var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                        await georestClient.AddInstructorAsync(viewModel);

                        result = RedirectToAction(nameof(Index));
                    }
                    catch (SwaggerException se)
                    {
                        ModelState.AddModelError("", se.Message);
                    }
                }
            }

            return result;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            InstructorViewModel fetchedInstructor = null;

            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                try
                {
                    var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                    fetchedInstructor = await georestClient.GetInstructorByIdAsync(id);
                }
                catch (SwaggerException se)
                {
                    ModelState.AddModelError("", se.Message);
                }
            }
            return View(fetchedInstructor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(InstructorViewModel viewModel)
        {
            IActionResult result = View();

            if (ModelState.IsValid)
            {
                using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
                {
                    try
                    {
                        var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                        await georestClient.UpdateInstructorAsync(viewModel.Id, Mapper.Map<InstructorInputViewModel>(viewModel));

                        result = RedirectToAction(nameof(Index));
                    }
                    catch (SwaggerException se)
                    {
                        ModelState.AddModelError("", se.Message);
                    }
                }
            }

            return result;
        }

        public async Task<IActionResult> Delete(int id)
        {
            IActionResult result = View();
            using (var httpClient = ClientFactory.CreateClient("GeorestApi"))
            {
                try
                {
                    var georestClient = new GeorestClient(httpClient.BaseAddress.ToString(), httpClient);
                    await georestClient.DeleteInstructorAsync(id);

                    result = RedirectToAction(nameof(Index));
                }
                catch (SwaggerException se)
                {
                    ModelState.AddModelError("", se.Message);
                }
            }

            return result;
        }
    }
}

src/Georest.Web/Views/InstructorLabs/Add.cshtml
@model InstructorLabInputViewModel

<div asp-validation-summary="All"></div>
<form asp-route="Add">
    <div class="field">
        <label class="label" asp-for="Title">Lab Title</label>
        <div class="control">
            <input class="input" type="text" asp-for="Title" />
        </div>
    </div>
    <div class="field">
        <label class="label" asp-for="InstructorId">Instructor ID</label>
        <div class="control">
            <input class="input" type="text" asp-for="InstructorId" />
        </div>
    </div>
    <div class="field">
        <label class="label" asp-for="ExerciseIds">Instructor ID</label>
        <div class="control">
            <input class="input" type="text" asp-for="InstructorId" />
        </div>
    </div>
    <div class="field">
        <div class="control is-grouped">
            <button class="button is-primary">Submit</button>
        </div>
        <div class="control">
            <a asp-controller="InstructorLabs" asp-action="Index" class="button is-light">Cancel</a>
        </div>
    </div>
</form>

src/Georest.Web/Views/InstructorLabs/Edit.cshtml
@model InstructorLabViewModel

<div asp-validation-summary="All"></div>
<form asp-route="Edit">
    <input asp-for="Id" type="hidden" />
    <div class="field">
        <label class="label" asp-for="Title">Lab Title</label>
        <div class="control">
            <input class="input" type="text" asp-for="Title" />
        </div>
    </div>
    <div class="field">
        <label class="label" asp-for="InstructorId">Instructor ID</label>
        <div class="control">
            <input class="input" type="text" asp-for="InstructorId" />
        </div>
    </div>
    <div class="field is-grouped">
        <div class="control">
            <button class="button is-primary">Submit</button>
        </div>
        <div class="control">
            <a asp-controller="Instructors" asp-action="Index" class="button is-light">Cancel</a>
        </div>
    </div>
</form>

src/Georest.Web/Views/InstructorLabs/Index.cshtml
<h1 class="heading is-size-3 is-bold">Instructor Labs<br /></h1>
<ul>
    @if (ViewBag.InstructorLabs.Count == 0)
    {
        <li>No Labs</li>
    }
    @foreach (var instructorLab in ViewBag.InstructorLabs)
    {
        <li>
            <br />
            <h1 class="heading is-size-4 is-bold">Lab:@instructorLab.Id @instructorLab.Title</h1>
            <a class="button" asp-action="edit" asp-route-id="@instructorLab.Id">Edit</a>
            <a class="button is-danger" asp-action="delete" asp-route-id="@instructorLab.Id" onclick="return confirm('Are you sure you want to delete the lab @instructorLab.Title?')">Delete</a>
        </li>
    }
</ul>
<a asp-controller="InstructorLabs" asp-action="Add" class="button is-primary">Add Lab</a>